### ISSUE TITLE
NullPointer when player lose connection in the game

### ISSUE THREAD

**Issue by Taka-sab** [erozabesu/YPLKart#39]
[YPLKart] Task #10 for YPLKart v1.0.9 generated an exception
java.lang.NullPointerException
	at com.github.erozabesu.yplkart.RaceManager.getRace(RaceManager.java:191) ~[?:?]
	at com.github.erozabesu.yplkart.RaceManager.isEntry(RaceManager.java:364) ~[?:?]
	at com.github.erozabesu.yplkart.Object.Circuit.isRaceEnd(Circuit.java:138) ~[?:?]
	at com.github.erozabesu.yplkart.Object.Circuit$2.run(Circuit.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-2f787bd-501372f]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [mc.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [mc.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [mc.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [mc.jar:git-Spigot-2f787bd-501372f]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [mc.jar:git-Spigot-2f787bd-501372f]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]

**Comment by erozabesu** [comment]
ご報告ありがとうございます。
次バージョンで修正します。

**Comment by erozabesu** [comment]
Fixed issue c78418cb79f3c7cefe16098dda114c48bb01accf
